### ISSUE TITLE
Selective text annotations in plotnine

### ISSUE THREAD

**Issue by jessieblaeser** [jsoma/plotnine-reference#1]
I'd love to go over how to create text annotations for subsets of a df. For example, in the mtcars dataset, if we want to highlight the five fastest cars on a graph that shows qsec vs mpg, how might we do that? Or, if we want to show the cars that optimize both qsec and mpg the best out of the entire list of cars, how would we find those vehicles and properly label them? 

Also, what are ways to make the labels pretty/not interfere with one another?

**Comment by jsoma** [comment]
Finding what you want to annotate is going to happen in pandas, but just pushed up docs for the rest:

* https://jsoma.github.io/plotnine-reference/annotations/selective-annotations/
* https://jsoma.github.io/plotnine-reference/annotations/outline-text/
* https://jsoma.github.io/plotnine-reference/annotations/overlapping-automatic-positioning/
